name: push container image

on:
  push:
    branches:
      - "main"

  workflow_dispatch: {}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/lirlia/web-summarizer:latest, ghcr.io/lirlia/web-summarizer:${{ github.sha }}
